# Generated by Django 2.1.7 on 2019-03-03 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='myuser',
            name='first_name',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='organization',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'renter'), (2, 'proxyrenter'), (3, 'groundskeeper'), (4, 'employee'), (5, 'admin')], default=1),
        ),
        migrations.AddField(
            model_name='myuser',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='street_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Street address'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Zip code'),
        ),
    ]
