# Generated by Django 2.1.7 on 2019-04-26 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parkAvail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text='Day of the event', verbose_name='Day of the event')),
                ('notes', models.TextField(blank=True, help_text='Textual Notes', null=True, verbose_name='Textual Notes')),
                ('Team_Name', models.CharField(blank=True, help_text='Team name', max_length=255, null=True, verbose_name='Team Name')),
                ('Size_of_the_team', models.CharField(blank=True, help_text='Capacity', max_length=3, null=True, verbose_name='size of the team')),
                ('Name_of_the_organization', models.CharField(blank=True, help_text='Organization name', max_length=100, null=True, verbose_name='Name of the Organization')),
                ('braintree_id', models.CharField(blank=True, max_length=150)),
                ('timeslot', models.CharField(blank=True, choices=[('M1', 'M1- 6.00 A.M to 8.00 A.M'), ('M2', 'M2- 8.15 A.M to 10.15 A.M'), ('M3', 'M3- 10.30 A.M to 12.30 P.M'), ('E1', 'E1- 3.00 P.M to 5.00 P.M'), ('E2', 'E2- 5.15 P.M to 7.15 P.M')], default='m', help_text='Available Timeslot', max_length=3)),
                ('park_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='park_name', to='parkAvail.Park')),
                ('prop_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prop_name', to='parkAvail.Prop')),
                ('renter_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renter_email', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scheduling',
                'verbose_name_plural': 'Scheduling',
            },
        ),
    ]
