# Generated by Django 2.1.7 on 2019-03-28 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parkAvail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text='Day of the event', verbose_name='Day of the event')),
                ('notes', models.TextField(blank=True, help_text='Textual Notes', null=True, verbose_name='Textual Notes')),
                ('timeslot', models.CharField(blank=True, choices=[('M1', '6.00 A.M to 8.00 A.M'), ('M2', '8.15 A.M to 10.15 A.M'), ('M3', '10.30 A.M to 12.30 P.M'), ('E1', '3.00 P.M to 5.00 P.M'), ('E2', '5.15 P.M to 7.15 P.M')], default='m', help_text='Available Timeslot', max_length=3)),
                ('prop_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prop_name', to='parkAvail.Prop')),
            ],
            options={
                'verbose_name': 'Scheduling',
                'verbose_name_plural': 'Scheduling',
            },
        ),
    ]
