# Generated by Django 2.1.7 on 2019-04-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Name_of_the_organization',
            field=models.CharField(blank=True, help_text='Organization name', max_length=100, null=True, verbose_name='Name of the Organization'),
        ),
        migrations.AddField(
            model_name='event',
            name='Size_of_the_team',
            field=models.CharField(blank=True, help_text='Capacity', max_length=3, null=True, verbose_name='size of the team'),
        ),
        migrations.AddField(
            model_name='event',
            name='Team_Name',
            field=models.CharField(blank=True, help_text='Team name', max_length=255, null=True, verbose_name='Team Name'),
        ),
    ]
