# Generated by Django 2.1.7 on 2019-03-30 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservSystem', '0002_groundskeeper'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroundsKeeper',
        ),
    ]
