# Generated by Django 2.1.7 on 2019-04-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservSystem', '0002_auto_20190401_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='timeslot',
            field=models.CharField(blank=True, choices=[('M1', 'M1- 6.00 A.M to 8.00 A.M'), ('M2', 'M2- 8.15 A.M to 10.15 A.M'), ('M3', 'M3- 10.30 A.M to 12.30 P.M'), ('E1', 'E1- 3.00 P.M to 5.00 P.M'), ('E2', 'E2- 5.15 P.M to 7.15 P.M')], default='m', help_text='Available Timeslot', max_length=3),
        ),
    ]
