# Generated by Django 2.1.7 on 2019-04-20 20:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parkAvail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_number', models.CharField(max_length=50)),
                ('Report_Time_Date', models.DateTimeField(default=datetime.datetime(2019, 4, 20, 15, 15, 27, 86063), help_text='Report Time&Date')),
                ('Property_Status_Description', models.TextField(max_length=10)),
                ('Personnel_Time', models.CharField(blank=True, choices=[('1hr', '1hr- Good'), ('2hrs', '2hrs- Better'), ('5hrs', '5hrs- Awful')], default='--', help_text='Personnel Time Spent', max_length=20)),
                ('Expenses', models.CharField(blank=True, choices=[('Good', '$2'), ('Better', '$10'), ('Awful', '$50')], default='--', help_text='Expenses', max_length=20)),
                ('Status', models.CharField(blank=True, choices=[('1', 'Pending'), ('2', 'Successful')], default='1', help_text='Payment status', max_length=20)),
                ('comments', models.TextField(blank=True, default='', max_length=200)),
                ('park_name', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='parkAvail.Park', verbose_name='park_name')),
                ('property_name', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='parkAvail.Prop', verbose_name='property_name')),
            ],
            options={
                'verbose_name_plural': 'Field Condition',
            },
        ),
    ]
