# Generated by Django 2.1.7 on 2019-03-30 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroundKeeper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcondition',
            name='property_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='parkAvail.Prop'),
        ),
    ]
