# Generated by Django 2.1.7 on 2019-04-26 06:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('GroundKeeper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcondition',
            name='Report_Time_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 26, 6, 55, 27, 66717, tzinfo=utc), help_text='Report Time&Date'),
        ),
    ]
