# Generated by Django 2.1.7 on 2019-04-20 23:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundKeeper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcondition',
            name='Report_Time_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 20, 18, 58, 53, 121810), help_text='Report Time&Date'),
        ),
    ]
