# Generated by Django 2.1.7 on 2019-04-07 05:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundKeeper', '0002_auto_20190407_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldcondition',
            name='updated_date',
        ),
        migrations.AlterField(
            model_name='fieldcondition',
            name='Report_Time_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 7, 0, 24, 7, 995276), help_text='Report Time&Date'),
        ),
    ]
