# Generated by Django 2.1.7 on 2019-03-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundKeeper', '0002_auto_20190330_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcondition',
            name='comments',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
