# Generated by Django 2.1.7 on 2019-04-20 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundKeeper', '0002_auto_20190420_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcondition',
            name='Report_Time_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 20, 15, 17, 47, 106814), help_text='Report Time&Date'),
        ),
    ]
