# Generated by Django 2.1.7 on 2019-04-24 07:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservSystem', '0001_initial'),
        ('GroundKeeper', '0002_auto_20190424_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldcondition',
            name='reservation_number',
        ),
        migrations.AddField(
            model_name='fieldcondition',
            name='event_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservSystem.Event'),
        ),
        migrations.AlterField(
            model_name='fieldcondition',
            name='Report_Time_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 24, 2, 57, 11, 432033), help_text='Report Time&Date'),
        ),
    ]
