# Generated by Django 2.1.7 on 2019-04-24 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundKeeper', '0003_auto_20190424_0257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldcondition',
            old_name='event_id',
            new_name='reservation_number',
        ),
        migrations.AlterField(
            model_name='fieldcondition',
            name='Report_Time_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 24, 3, 33, 41, 586282), help_text='Report Time&Date'),
        ),
    ]
