# Generated by Django 2.1.7 on 2019-04-07 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundKeeper', '0003_auto_20190407_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcondition',
            name='Report_Time_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 7, 0, 36, 13, 867560), help_text='Report Time&Date'),
        ),
    ]
