# Generated by Django 2.1.7 on 2019-04-20 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundKeeper', '0003_auto_20190420_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcondition',
            name='Report_Time_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 20, 14, 57, 12, 563381), help_text='Report Time&Date'),
        ),
    ]
