# Generated by Django 2.1.7 on 2019-04-24 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundKeeper', '0004_auto_20190424_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcondition',
            name='Report_Time_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 24, 3, 39, 37, 466865), help_text='Report Time&Date'),
        ),
    ]
