# Generated by Django 2.1.7 on 2019-05-01 16:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('GroundKeeper', '0005_auto_20190426_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcondition',
            name='Report_Time_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 1, 16, 16, 55, 261613, tzinfo=utc), help_text='Report Time&Date'),
        ),
    ]
