# Generated by Django 2.1.7 on 2019-04-20 03:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundKeeper', '0005_auto_20190419_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcondition',
            name='Report_Time_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 19, 22, 12, 47, 935336), help_text='Report Time&Date'),
        ),
    ]
