# Generated by Django 2.1.7 on 2019-04-07 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundKeeper', '0005_auto_20190407_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcondition',
            name='Report_Time_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 7, 18, 39, 42, 455063), help_text='Report Time&Date'),
        ),
    ]
