# Generated by Django 2.1.7 on 2019-04-21 00:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundKeeper', '0005_auto_20190420_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcondition',
            name='Report_Time_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 20, 19, 43, 42, 740319), help_text='Report Time&Date'),
        ),
    ]
