# Generated by Django 2.1.7 on 2019-04-20 04:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundKeeper', '0007_auto_20190419_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcondition',
            name='Report_Time_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 19, 23, 21, 57, 338594), help_text='Report Time&Date'),
        ),
    ]
