# Generated by Django 2.1.7 on 2019-04-20 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundKeeper', '0008_auto_20190419_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcondition',
            name='Report_Time_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 19, 23, 42, 52, 521884), help_text='Report Time&Date'),
        ),
    ]
