# Generated by Django 2.1.7 on 2019-04-21 00:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundKeeper', '0008_auto_20190420_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcondition',
            name='Report_Time_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 20, 19, 59, 47, 937789), help_text='Report Time&Date'),
        ),
    ]
