# Generated by Django 2.1.7 on 2019-04-08 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundKeeper', '0008_auto_20190407_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcondition',
            name='Report_Time_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 7, 19, 33, 30, 263261), help_text='Report Time&Date'),
        ),
    ]
