# Generated by Django 2.1.7 on 2019-04-24 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundKeeper', '0009_auto_20190420_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcondition',
            name='Report_Time_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 24, 9, 34, 55, 712802), help_text='Report Time&Date'),
        ),
    ]
