# Generated by Django 2.1.8 on 2019-04-24 20:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('GroundKeeper', '0009_auto_20190424_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcondition',
            name='Report_Time_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 24, 20, 17, 44, 787824, tzinfo=utc), help_text='Report Time&Date'),
        ),
    ]
