# Generated by Django 2.1.7 on 2019-04-10 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundKeeper', '0009_auto_20190407_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldcondition',
            name='Status',
            field=models.CharField(blank=True, choices=[('1', 'Pending'), ('2', 'Successful')], help_text='Payment status', max_length=20),
        ),
        migrations.AlterField(
            model_name='fieldcondition',
            name='Report_Time_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 9, 22, 30, 52, 353496), help_text='Report Time&Date'),
        ),
    ]
