# Generated by Django 2.1.7 on 2019-04-10 03:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundKeeper', '0011_auto_20190409_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcondition',
            name='Report_Time_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 9, 22, 33, 1, 810727), help_text='Report Time&Date'),
        ),
        migrations.AlterField(
            model_name='fieldcondition',
            name='Status',
            field=models.CharField(blank=True, choices=[('1', 'Pending'), ('2', 'Successful')], default='1', help_text='Payment status', max_length=20),
        ),
    ]
