# Generated by Django 2.1.7 on 2019-04-18 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundKeeper', '0012_auto_20190409_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcondition',
            name='Report_Time_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 18, 11, 21, 50, 333033), help_text='Report Time&Date'),
        ),
    ]
