# Generated by Django 2.1.7 on 2019-04-20 01:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundKeeper', '0013_auto_20190418_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcondition',
            name='Report_Time_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 19, 20, 45, 56, 347618), help_text='Report Time&Date'),
        ),
    ]
