# Generated by Django 2.1.7 on 2019-04-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkAvail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prop',
            name='image',
            field=models.ImageField(blank=True, upload_to='https://afrteam.s3.amazonaws.com/static/props/%Y/%m/%d'),
        ),
    ]
