# Generated by Django 2.1.7 on 2019-04-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkAvail', '0002_auto_20190424_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prop',
            name='image',
            field=models.ImageField(blank=True, upload_to='props/%Y/%m/%d'),
        ),
    ]
