# Generated by Django 2.1.7 on 2019-03-30 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkAvail', '0002_fieldcondition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FieldCondition',
        ),
    ]
