# Generated by Django 2.0.5 on 2019-03-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkAvail', '0003_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='slug',
            field=models.SlugField(default=231, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(default=232, max_length=200),
            preserve_default=False,
        ),
    ]
