# Generated by Django 2.1.7 on 2019-03-13 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkAvail', '0004_auto_20190308_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='park',
            options={'ordering': ('park_name',), 'verbose_name': 'park', 'verbose_name_plural': 'parks'},
        ),
        migrations.AlterField(
            model_name='property',
            name='park_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='park', to='parkAvail.Park'),
        ),
    ]
